name: go2rl
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.10.19=hcd7f573_2_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - tzdata=2025b=h78e105d_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - Deprecated==1.3.1
    - GitPython==3.1.45
    - ImageIO==2.37.2
    - Jinja2==3.1.6
    - Markdown==3.10
    - MarkupSafe==3.0.3
    - OpenEXR==3.4.3
    - PyGEL3D==0.6.1
    - PyOpenGL==3.1.10
    - PyYAML==6.0.3
    - Pygments==2.19.2
    - Werkzeug==3.1.3
    - absl-py==2.3.1
    - annotated-types==0.7.0
    - anyio==4.11.0
    - asttokens==3.0.1
    - av==16.0.1
    - black==25.11.0
    - certifi==2025.11.12
    - cffi==2.0.0
    - charset-normalizer==3.4.4
    - click==8.3.1
    - coacd==1.0.7
    - colorama==0.4.6
    - contourpy==1.3.2
    - cycler==0.12.1
    - dataclasses-json==0.6.7
    - decorator==5.2.1
    - dill==0.4.0
    - etils==1.13.0
    - exceptiongroup==1.3.0
    - execnet==2.1.2
    - executing==2.2.1
    - fast_simplification==0.1.12
    - filelock==3.20.0
    - fonttools==4.60.1
    - freetype-py==2.5.1
    - fsspec==2025.10.0
    - genesis-world==0.3.7
    - gitdb==4.0.12
    - glfw==2.10.0
    - grpcio==1.76.0
    - gstaichi==4.0.0
    - h11==0.16.0
    - hf-xet==1.2.0
    - httpcore==1.0.9
    - httpx==0.28.1
    - huggingface_hub==1.1.4
    - idna==3.11
    - imageio-ffmpeg==0.6.0
    - importlib_resources==6.5.2
    - iniconfig==2.3.0
    - ipython==8.37.0
    - jedi==0.19.2
    - kiwisolver==1.4.9
    - lazy_loader==0.4
    - libigl==2.6.1
    - llvmlite==0.45.1
    - markdown-it-py==4.0.0
    - marshmallow==3.26.1
    - matplotlib==3.10.7
    - matplotlib-inline==0.2.1
    - mdurl==0.1.2
    - ml_dtypes==0.5.3
    - moviepy==2.2.1
    - mpmath==1.3.0
    - mujoco==3.3.7
    - mypy_extensions==1.1.0
    - networkx==3.4.2
    - numba==0.62.1
    - numpy==2.2.6
    - onnx==1.19.1
    - opencv-python==4.12.0.88
    - packaging==25.0
    - parso==0.8.5
    - pathspec==0.12.1
    - pexpect==4.9.0
    - pillow==11.3.0
    - platformdirs==4.5.0
    - plotly==5.24.1
    - pluggy==1.6.0
    - pooch==1.8.2
    - proglog==0.1.12
    - prompt_toolkit==3.0.52
    - protobuf==6.33.1
    - psutil==7.1.3
    - ptyprocess==0.7.0
    - pure_eval==0.2.3
    - py==1.11.0
    - py-cpuinfo==9.0.0
    - pycollada==0.9.2
    - pycparser==2.23
    - pydantic==2.12.4
    - pydantic_core==2.41.5
    - pyglet==2.1.11
    - pygltflib==1.16.0
    - pymeshlab==2025.7
    - pyparsing==3.2.5
    - pysplashsurf==0.12.0.2
    - pytest==9.0.1
    - pytest-forked==1.6.0
    - pytest-print==1.2.0
    - pytest-random-order==1.2.0
    - pytest-rerunfailures==16.1
    - pytest-xdist==3.8.0
    - python-dateutil==2.9.0.post0
    - python-dotenv==1.2.1
    - pytokens==0.3.0
    - pyvista==0.46.4
    - requests==2.32.5
    - rich==14.2.0
    - rsl-rl-lib==2.2.4
    - rtree==1.4.1
    - scikit-image==0.25.2
    - scipy==1.15.3
    - scooby==0.11.0
    - sentry-sdk==2.44.0
    - shellingham==1.5.4
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - stack-data==0.6.3
    - sympy==1.14.0
    - syrupy==5.0.0
    - tenacity==9.1.2
    - tensorboard==2.20.0
    - tensorboard-data-server==0.7.2
    - tetgen==0.6.7
    - tifffile==2025.5.10
    - tomli==2.3.0
    - torch==2.9.1
    - torchvision==0.24.1
    - tqdm==4.67.1
    - traitlets==5.14.3
    - trimesh==4.9.0
    - typer-slim==0.20.0
    - typing-inspect==0.9.0
    - typing-inspection==0.4.2
    - typing_extensions==4.15.0
    - urllib3==2.5.0
    - vtk==9.5.2
    - wandb==0.23.0
    - wcwidth==0.2.14
    - wrapt==2.0.1
    - z3-solver==4.15.4.0
    - zipp==3.23.0

prefix: "/opt/homebrew/opt/miniforge/envs/go2rl"
